### ISSUE TITLE
Cannot compile modified recipe - GStreamer 1.14 + GIR

### ISSUE THREAD

**Issue by KaloyanP** [conda-forge/gst-plugins-base-feedstock#5]
Hello,

I am currently trying to update this recipe to the newest version of GStreamer AND also make it available through GObject Introspection so that I can use Python bindings in conda environments. End goal of the entire saga is to have all plugins accessible through GObject in conda. 

The problem I am having is that I can't build anything beyond the GStreamer core module - anything else and it complains about missing libraries.

I have the updated recipes in my profile:

https://github.com/KaloyanP/gst-plugins-base-feedstock/tree/update-version-with-gir
https://github.com/KaloyanP/gstreamer-feedstock/tree/update-version-with-gir

The changes I have made have been to update the version and the SHA, and then updating the build script as follows:

- Add necessary dependencies
- Add the --enable-introspection flag on the build
- Remove the --data-tools-dir argument so that all the build files are included in the final package (I don't really care about size, so long as it works)

The `gst-plugins-base-feedstock` fails with the following error on my machine. I have confirmed that the file `dyld: Library not loaded: @rpath/libgstbase-1.0.0.dylib` is indeed in the `placeholder/lib` directory - at this point, I am lost as to what I should do, because it seems to be a conda issue!

```
/Library/Developer/CommandLineTools/usr/bin/make  all-am
  CC       libgsttag_1.0_la-gstvorbistag.lo
  CC       libgsttag_1.0_la-gstid3tag.lo
  CC       libgsttag_1.0_la-gstxmptag.lo
  CC       libgsttag_1.0_la-gstexiftag.lo
  CC       libgsttag_1.0_la-lang.lo
  CC       libgsttag_1.0_la-licenses.lo
  CC       libgsttag_1.0_la-tags.lo
  CC       libgsttag_1.0_la-gsttagdemux.lo
  CC       libgsttag_1.0_la-gsttagmux.lo
  CC       libgsttag_1.0_la-gsttageditingprivate.lo
  CC       libgsttag_1.0_la-id3v2.lo
  CC       libgsttag_1.0_la-id3v2frames.lo
  CC       libgsttag_1.0_la-xmpwriter.lo
  CC       libgsttag_1.0_la-tag-enumtypes.lo
  CCLD     libgsttag-1.0.la
  GEN      GstTag-1.0.gir
g-ir-scanner: link: ../../../libtool --mode=link --tag=CC gcc -o /Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/work/gst-libs/gst/tag/tmp-introspectw3hhn6vc/GstTag-1.0 -export-dynamic -I/Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -g -O2 /Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/work/gst-libs/gst/tag/tmp-introspectw3hhn6vc/GstTag-1.0.o -L. libgsttag-1.0.la -L/Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -lgio-2.0 -lgmodule-2.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation
libtool: link: gcc -o /Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/work/gst-libs/gst/tag/tmp-introspectw3hhn6vc/.libs/GstTag-1.0 -I/Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/include -g -O2 /Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/work/gst-libs/gst/tag/tmp-introspectw3hhn6vc/GstTag-1.0.o -Wl,-framework -Wl,CoreFoundation  -L. ./.libs/libgsttag-1.0.dylib -L/Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -lz -lgio-2.0 /Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libgstbase-1.0.dylib /Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libgstreamer-1.0.dylib -lgmodule-2.0 -ldl -lgobject-2.0 -lglib-2.0 /Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libintl.dylib -lc
dyld: Library not loaded: @rpath/libgstbase-1.0.0.dylib
  Referenced from: /Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/work/gst-libs/gst/tag/tmp-introspectw3hhn6vc/.libs/GstTag-1.0
  Reason: image not found
Command '['/Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/work/gst-libs/gst/tag/tmp-introspectw3hhn6vc/GstTag-1.0', '--introspect-dump=/Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/work/gst-libs/gst/tag/tmp-introspectw3hhn6vc/functions.txt,/Users/kpashov/anaconda3/conda-bld/gst-plugins-base_1523193383829/work/gst-libs/gst/tag/tmp-introspectw3hhn6vc/dump.xml']' died with <Signals.SIGABRT: 6>.
make[5]: *** [GstTag-1.0.gir] Error 1
make[4]: *** [all] Error 2
make[3]: *** [tag] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
```

**Comment by mingwandroid** [comment]
This is very unlikely to be a 'conda' issue (conda is a package manager after all). It's also very unlikely to be a 'conda-build' issue (since that just does what it is told to by the build scripts).

Building C and C++ software is fairly complex and requires a good level of understanding about how compilers and operating systems work.

You probably need to add `-Wl,-rpath,${PREFIX}/lib` to CFLAGS and/or CXXFLAGS.

**Comment by KaloyanP** [comment]
@mingwandroid, I have learned that building C packages with limited knowledge of how to build C packages is really hard - that's why I am trying to use conda in the first place :). However, as the package I need is not available from any channel (i.e. PYGobject introspection won't pick gstreamer bindings), I need to build it myself anyway. Or go back to using pip and virtualenv, which I don't want to do.

Thank you for the quick reply - the package now builds with these switches, but fails its tests. The tests just check for the shared objects (.so) that should be generated at some point during the process. Unfortunately, any references to them are conspicuously missing from any of the logs that the library outputs.

Interestingly, `gst-inspect-1.0` does report that all the plugins in gst-plugins-base are available.

Do you have any pointers where I should look to resolve this new problem?

**Comment by mingwandroid** [comment]
I find the logs from most `conda-forge` builds to be pretty useless in most cases because they are rarely verbose (both CMake and Autotools require explicitly enabling that in the build phase via `VERBOSE=1` or `V=1` when driven via GNU make).

To get back to your problem, it seems that you have not added the `toolchain` package which is responsible for setting `CFLAGS` and `CXXFLAGS`:

https://github.com/KaloyanP/gstreamer-feedstock/blob/update-version-with-gir/recipe/meta.yaml

.. on Anaconda Defaults we handle compilers differently so if you are looking to build packages that are compatible with AD you should refer to https://github.com/AnacondaRecipes/gstreamer-feedstock/blob/master/recipe/meta.yaml

**Comment by KaloyanP** [comment]
@mingwandroid I see, I will rebase on top of gstreamer core and toil away at it.

Is this package (gst-plugins-base) going to be maintained if gstreamer core already includes its binaries?

**Comment by mingwandroid** [comment]
Not sure where gstreamer-core enters the picture here nor how your question about maintenance relates to the issue.

They are and will remain separate packages without any overlapping files.

**Comment by KaloyanP** [comment]
The gstreamer (gstreamer-core) you pointed to on defaults already includes the build for gst-plugins-base in it, starting with its latest commit. It also seems that it is further ahead (at 1.14) than the conda-forge version (1.08).

I am just assuming that at some point, the conda-forge packages will follow the same path as Anaconda Defaults.

**Comment by mingwandroid** [comment]
No, the recipe I pointed you at (`gstreamer`, not `gstreamer-core`, the word `core` appears nowhere) generates split packages. This is a new feature of conda-build 3 and reduces recipe maintenance burden and build time greatly.

There are still two packages generated (see `outputs:`).

**Comment by mingwandroid** [comment]
Also, I was not suggesting you to rebase on top of the recipe for defaults, it's up to you whether you want to be compatible with Anaconda Defaults or with conda-forge. At the moment you can't generally have both unfortunately.

**Comment by KaloyanP** [comment]
I have been trying to to add support for OSX 10.12, move it to 1.14, and add GObject Introspection. Unfortunately, I can't get any of these to work, probably because compiling on a different platform is hard. I will update if I succeed in this.

**Comment by mingwandroid** [comment]
The gstreamer packages on defaults are built with introspection on macOS and Linux Please refer to https://github.com/AnacondaRecipes/gstreamer-feedstock/blob/master/recipe

**Comment by ocefpaf** [comment]
Closing this as stale.
